### ISSUE TITLE
Mention standard support in the README

### ISSUE THREAD

**Issue by rouson** [fortesg/fortrantestgenerator#1]
Please add a statement to the README.me file indicating what Fortran standards fortrantestgenerator supports.  The README specifically mentions legacy code, but does not mention modern Fortran or whether a specific standard might serve as your chosen boundary between the legacy and modern.  I have not read the cited paper in detail, but at first glance see .f90 extensions in one figure, which suggests that the tool at least supports Fortran 90.  Reference 17 in the cited paper is a Fortran 2003 handbook so hopefully that's an indication that fortrantestgenerator supports Fortran 2003.  The current standard is Fortran 2008 and the next standard, Fortran 2015, exists in a [draft] that will likely be published later this year.

[draft]: http://isotc.iso.org/livelink/livelink?func=ll&objId=18770270&objAction=Open

**Comment by chovyy** [comment]
Done. 

In general, the source code analysis makes only a very few assumptions about the syntax, so all modern Fortran standards since Fortran90 are generally supported. But not every single feature from every single standard has been tested so far.
