### ISSUE TITLE
[SB2 frontend] 2.3.1 is now not capturing required parts of complex derived types (2.3.0 was OK)

### ISSUE THREAD

**Issue by vectorflux** [fortesg/fortrantestgenerator#13]
Unfortunately 2.3.1 has introduced problems in capturing all that is needed in complex derived types like p_prog and p_patch.  I'm working with 2 examples:

  FortranTestGenerator.py -c mo_solve_nonhydro solve_nh
  FortranTestGenerator.py -c mo_velocity_advection velocity_tendencies

The velocity_tendencies example is working with 2.3.0, albeit with the #ifdef ... #endif problem mentioned in another ticket.   With the appropriate fix for that issue, the capture works and produced the following *p_patch*.dat and *p_prog*.dat files

ftg_velocity_tendencies_input_0_p_patch%cells%area.dat
ftg_velocity_tendencies_input_0_p_patch%cells%decomp_info%owner_mask.dat
ftg_velocity_tendencies_input_0_p_patch%cells%edge_blk.dat
ftg_velocity_tendencies_input_0_p_patch%cells%edge_idx.dat
ftg_velocity_tendencies_input_0_p_patch%cells%end_block.dat
ftg_velocity_tendencies_input_0_p_patch%cells%end_index.dat
ftg_velocity_tendencies_input_0_p_patch%cells%neighbor_blk.dat
ftg_velocity_tendencies_input_0_p_patch%cells%neighbor_idx.dat
ftg_velocity_tendencies_input_0_p_patch%cells%start_block.dat
ftg_velocity_tendencies_input_0_p_patch%cells%start_index.dat
ftg_velocity_tendencies_input_0_p_patch%edges%area_edge.dat
ftg_velocity_tendencies_input_0_p_patch%edges%cell_blk.dat
ftg_velocity_tendencies_input_0_p_patch%edges%cell_idx.dat
ftg_velocity_tendencies_input_0_p_patch%edges%end_block.dat
ftg_velocity_tendencies_input_0_p_patch%edges%end_index.dat
ftg_velocity_tendencies_input_0_p_patch%edges%f_e.dat
ftg_velocity_tendencies_input_0_p_patch%edges%inv_dual_edge_length.dat
ftg_velocity_tendencies_input_0_p_patch%edges%inv_primal_edge_length.dat
ftg_velocity_tendencies_input_0_p_patch%edges%quad_blk.dat
ftg_velocity_tendencies_input_0_p_patch%edges%quad_idx.dat
ftg_velocity_tendencies_input_0_p_patch%edges%start_block.dat
ftg_velocity_tendencies_input_0_p_patch%edges%start_index.dat
ftg_velocity_tendencies_input_0_p_patch%edges%tangent_orientation.dat
ftg_velocity_tendencies_input_0_p_patch%edges%vertex_blk.dat
ftg_velocity_tendencies_input_0_p_patch%edges%vertex_idx.dat
ftg_velocity_tendencies_input_0_p_patch%id.dat
ftg_velocity_tendencies_input_0_p_patch%nblks_c.dat
ftg_velocity_tendencies_input_0_p_patch%nblks_e.dat
ftg_velocity_tendencies_input_0_p_patch%nblks_v.dat
ftg_velocity_tendencies_input_0_p_patch%n_childdom.dat
ftg_velocity_tendencies_input_0_p_patch%nlev.dat
ftg_velocity_tendencies_input_0_p_patch%nlevp1.dat
ftg_velocity_tendencies_input_0_p_patch%nshift.dat
ftg_velocity_tendencies_input_0_p_patch%verts%cell_blk.dat
ftg_velocity_tendencies_input_0_p_patch%verts%cell_idx.dat
ftg_velocity_tendencies_input_0_p_patch%verts%edge_blk.dat
ftg_velocity_tendencies_input_0_p_patch%verts%edge_idx.dat
ftg_velocity_tendencies_input_0_p_patch%verts%end_blk.dat
ftg_velocity_tendencies_input_0_p_patch%verts%end_block.dat
ftg_velocity_tendencies_input_0_p_patch%verts%end_index.dat
ftg_velocity_tendencies_input_0_p_patch%verts%start_blk.dat
ftg_velocity_tendencies_input_0_p_patch%verts%start_block.dat
ftg_velocity_tendencies_input_0_p_patch%verts%start_index.dat
ftg_velocity_tendencies_input_0_p_prog%vn.dat
ftg_velocity_tendencies_input_0_p_prog%w.dat

The replay worked fine with 2.3.0 and the test has been incorporated into the icon-standalone repository.  However, the capture with 2.3.1 only produces the following:

ftg_velocity_tendencies_input_0_p_patch%cells%area.dat
ftg_velocity_tendencies_input_0_p_patch%cells%decomp_info%owner_mask.dat
ftg_velocity_tendencies_input_0_p_patch%cells%edge_blk.dat
ftg_velocity_tendencies_input_0_p_patch%cells%edge_idx.dat
ftg_velocity_tendencies_input_0_p_patch%cells%end_block.dat
ftg_velocity_tendencies_input_0_p_patch%cells%neighbor_blk.dat
ftg_velocity_tendencies_input_0_p_patch%cells%neighbor_idx.dat
ftg_velocity_tendencies_input_0_p_patch%cells%start_block.dat
ftg_velocity_tendencies_input_0_p_patch%edges%area_edge.dat
ftg_velocity_tendencies_input_0_p_patch%edges%cell_blk.dat
ftg_velocity_tendencies_input_0_p_patch%edges%cell_idx.dat
ftg_velocity_tendencies_input_0_p_patch%edges%end_block.dat
ftg_velocity_tendencies_input_0_p_patch%edges%f_e.dat
ftg_velocity_tendencies_input_0_p_patch%edges%inv_dual_edge_length.dat
ftg_velocity_tendencies_input_0_p_patch%edges%inv_primal_edge_length.dat
ftg_velocity_tendencies_input_0_p_patch%edges%quad_blk.dat
ftg_velocity_tendencies_input_0_p_patch%edges%quad_idx.dat
ftg_velocity_tendencies_input_0_p_patch%edges%start_block.dat
ftg_velocity_tendencies_input_0_p_patch%edges%tangent_orientation.dat
ftg_velocity_tendencies_input_0_p_patch%edges%vertex_blk.dat
ftg_velocity_tendencies_input_0_p_patch%edges%vertex_idx.dat
ftg_velocity_tendencies_input_0_p_patch%id.dat
ftg_velocity_tendencies_input_0_p_patch%nblks_c.dat
ftg_velocity_tendencies_input_0_p_patch%nblks_e.dat
ftg_velocity_tendencies_input_0_p_patch%nblks_v.dat
ftg_velocity_tendencies_input_0_p_patch%nlev.dat
ftg_velocity_tendencies_input_0_p_patch%nlevp1.dat
ftg_velocity_tendencies_input_0_p_patch%nshift.dat

note for example the missing p_patch%verts%*.dat files.

This then manifests itself in the replay.  In ftg_solve_nh_test with the following error:

 FTG: *** Run test for solve_nh ***
 FTG INIT solve_nh ftg_solve_nh_input_0
FTG READ INPUT DATA solve_nh (0)
At line 1196 of file ../../../src/shr_horizontal/mo_icon_interpolation_scalar.f90
Fortran runtime error: Index '1' of dimension 2 of array 'ptr_patch%verts%start_blk' above upper bound of 0

(which makes sense, since p_patch%verts is not allocated or read).

In ftg_velocity_tendencies_test it gives a less clear message:

 FTG: *** Run test for solve_nh ***
 FTG INIT solve_nh ftg_solve_nh_input_0
FTG READ INPUT DATA solve_nh (0)
Serialbox: ERROR: field 'p_nh%prog(1)%vn' has rank 3 but field with rank 1 was passed
srun: error: nid03508: task 0: Exited with exit code 1
srun: Terminating job step 7725616.1

but it is very likely also linked to the missing files.

Thomas suggested that "ignore_bullshit" might play a role here.  If we set

  ignore_bullshit = .FALSE.

for example in the revised mo_solve_nonhydro.f90, then the capture produces *no* *p_patch*.dat files at all...

I think it is not related to the issue about adding => NULL() to every declaration of a pointer variable, since  (1) NULL() were added to all these derived types over a year ago, (2) The capture is being performed, (3) the 2.3.0 version is working.

Any help would be appreciated.

Best, --Will

**Comment by chovyy** [comment]
Thanks for reporting this issue with the FTG interface in [Serialbox2](https://github.com/eth-cscs/serialbox2). I will see how I can fix this asap.

**Comment by vectorflux** [comment]
I am trying to revert back to Serialbox2 2.3.0 and FTG 1.3.1, but I'm still getting the 'new' data files, e.g., p_patch%verts is not being written.  Not sure if I am just doing something stupid....

Looking at the output of FortranCallGraph, it appears it only analyzes the occurrences of p_patch in the target subroutine, and creates ftg_write statements for these.  It does not generate ftg_write statements for p_patch usage farther down the call tree.  Can this be?

This is the problem in my case:  p_patch%verts is, for example, not used in solve_nh, but is used at a lower level.  Of course, I could add the needed ftg_write statements by hand, but that would become a big job...

**Comment by vectorflux** [comment]
Addendum: now using fotrantestgenerator:master as opposed to release 1.4.0, and this appears to dump the parts of p_patch%verts that are needed.  But not sure if this is the only difference: I'm also using it in the framework of Philippe's extraction scripts, which might add some magic...  Now investigating...

**Comment by chovyy** [comment]
I don't think I can reproduce that.

With the latest version of FortranCallGraph, the following command: 

`./FortranCallGraph -cc -a all mo_velocity_advection velocity_tendencies`

returns the following result:

```
*** WARNING [UseTraversal] Source file not found for module: mtime_juliandelta (in: mtime_timedelta) ***
z_w_concorr_me
z_kin_hor_e
z_vt_ie
ntnd
istep
lvn_only
dtime
p_prog%vn (__mo_velocity_advection_MOD_velocity_tendencies, 222)
p_prog%w (__mo_velocity_advection_MOD_velocity_tendencies, 218)
p_patch%id (__mo_velocity_advection_MOD_velocity_tendencies, 172)
p_patch%n_childdom (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri => ptr_patch, 1195)
p_patch%nblks_c (__mo_velocity_advection_MOD_velocity_tendencies, 119)
p_patch%nblks_e (__mo_velocity_advection_MOD_velocity_tendencies, 122)
p_patch%nblks_v (__mo_velocity_advection_MOD_velocity_tendencies, 123)
p_patch%nlev (__mo_velocity_advection_MOD_velocity_tendencies, 117)
p_patch%nlevp1 (__mo_velocity_advection_MOD_velocity_tendencies, 118)
p_patch%nshift (__mo_velocity_advection_MOD_velocity_tendencies, 165)
p_patch%cells%area (__mo_velocity_advection_MOD_velocity_tendencies, 589)
p_patch%cells%edge_blk (__mo_velocity_advection_MOD_velocity_tendencies, 185)
p_patch%cells%edge_idx (__mo_velocity_advection_MOD_velocity_tendencies, 184)
p_patch%cells%end_block (__mo_velocity_advection_MOD_velocity_tendencies, 406)
p_patch%cells%end_index (__mo_loopindices_MOD_get_indices_c, 83)
p_patch%cells%neighbor_blk (__mo_velocity_advection_MOD_velocity_tendencies, 191)
p_patch%cells%neighbor_idx (__mo_velocity_advection_MOD_velocity_tendencies, 190)
p_patch%cells%start_block (__mo_velocity_advection_MOD_velocity_tendencies, 405)
p_patch%cells%start_index (__mo_loopindices_MOD_get_indices_c, 81)
p_patch%edges%area_edge (__mo_velocity_advection_MOD_velocity_tendencies, 690)
p_patch%edges%cell_blk (__mo_velocity_advection_MOD_velocity_tendencies, 182)
p_patch%edges%cell_idx (__mo_velocity_advection_MOD_velocity_tendencies, 181)
p_patch%edges%end_block (__mo_velocity_advection_MOD_velocity_tendencies, 234)
p_patch%edges%end_index (__mo_loopindices_MOD_get_indices_e, 136)
p_patch%edges%f_e (__mo_velocity_advection_MOD_velocity_tendencies, 648)
p_patch%edges%inv_dual_edge_length (__mo_velocity_advection_MOD_velocity_tendencies, 375)
p_patch%edges%inv_primal_edge_length (__mo_velocity_advection_MOD_velocity_tendencies, 375)
p_patch%edges%quad_blk (__mo_velocity_advection_MOD_velocity_tendencies, 194)
p_patch%edges%quad_idx (__mo_velocity_advection_MOD_velocity_tendencies, 193)
p_patch%edges%start_block (__mo_velocity_advection_MOD_velocity_tendencies, 233)
p_patch%edges%start_index (__mo_loopindices_MOD_get_indices_e, 134)
p_patch%edges%tangent_orientation (__mo_velocity_advection_MOD_velocity_tendencies, 375)
p_patch%edges%vertex_blk (__mo_velocity_advection_MOD_velocity_tendencies, 188)
p_patch%edges%vertex_idx (__mo_velocity_advection_MOD_velocity_tendencies, 187)
p_patch%verts%cell_blk (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri => ptr_patch, 1192)
p_patch%verts%cell_idx (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri => ptr_patch, 1191)
p_patch%verts%edge_blk (__mo_math_divrot_MOD_rot_vertex_ri => ptr_patch, 3522)
p_patch%verts%edge_idx (__mo_math_divrot_MOD_rot_vertex_ri => ptr_patch, 3521)
p_patch%verts%end_blk (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri => ptr_patch, 1197)
p_patch%verts%end_block (__mo_math_divrot_MOD_rot_vertex_ri => ptr_patch, 3526)
p_patch%verts%end_index (__mo_loopindices_MOD_get_indices_v => p_patch, 187)
p_patch%verts%start_blk (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri => ptr_patch, 1196)
p_patch%verts%start_block (__mo_math_divrot_MOD_rot_vertex_ri => ptr_patch, 3525)
p_patch%verts%start_index (__mo_loopindices_MOD_get_indices_v => p_patch, 185)
p_patch%cells%decomp_info%owner_mask (__mo_velocity_advection_MOD_velocity_tendencies, 584)
p_int%c_lin_e (__mo_velocity_advection_MOD_velocity_tendencies, 648)
p_int%cells_aw_verts (__mo_velocity_advection_MOD_velocity_tendencies, 218)
p_int%e_bln_c_s (__mo_velocity_advection_MOD_velocity_tendencies, 440)
p_int%geofac_grdiv (__mo_velocity_advection_MOD_velocity_tendencies, 690)
p_int%geofac_n2s (__mo_velocity_advection_MOD_velocity_tendencies, 589)
p_int%geofac_rot (__mo_math_divrot_MOD_rot_vertex_ri => ptr_int, 3556)
p_int%rbf_vec_coeff_e (__mo_velocity_advection_MOD_velocity_tendencies, 260)
p_metrics%coeff1_dwdz (__mo_velocity_advection_MOD_velocity_tendencies, 549)
p_metrics%coeff2_dwdz (__mo_velocity_advection_MOD_velocity_tendencies, 549)
p_metrics%coeff_gradekin (__mo_velocity_advection_MOD_velocity_tendencies, 648)
p_metrics%ddqz_z_full_e (__mo_velocity_advection_MOD_velocity_tendencies, 648)
p_metrics%ddqz_z_half (__mo_velocity_advection_MOD_velocity_tendencies, 511)
p_metrics%ddxn_z_full (__mo_velocity_advection_MOD_velocity_tendencies, 300)
p_metrics%ddxt_z_full (__mo_velocity_advection_MOD_velocity_tendencies, 300)
p_metrics%wgtfac_c (__mo_velocity_advection_MOD_velocity_tendencies, 477)
p_metrics%wgtfac_e (__mo_velocity_advection_MOD_velocity_tendencies, 273)
p_metrics%wgtfacq_e (__mo_velocity_advection_MOD_velocity_tendencies, 318)
p_diag%ddt_vn_adv (__mo_velocity_advection_MOD_velocity_tendencies, 648)
p_diag%ddt_w_adv (__mo_velocity_advection_MOD_velocity_tendencies, 549)
p_diag%dvn_ie_ubc (__mo_velocity_advection_MOD_velocity_tendencies, 328)
p_diag%max_vcfl_dyn (__mo_velocity_advection_MOD_velocity_tendencies, 728)
p_diag%vn_ie (__mo_velocity_advection_MOD_velocity_tendencies, 273)
p_diag%vt (__mo_velocity_advection_MOD_velocity_tendencies, 260)
p_diag%w_concorr_c (__mo_velocity_advection_MOD_velocity_tendencies, 477)
active_timers (__mo_real_timer_MOD_timer_stop, 533)
active_timers_top (__mo_real_timer_MOD_timer_stop, 533)
delta_i (__mo_real_timer_MOD_timer_stop, 522)
lextra_diffu (__mo_velocity_advection_MOD_velocity_tendencies, 207)
ltimer (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri, 1200)
lvert_nest (__mo_velocity_advection_MOD_velocity_tendencies, 165)
nflatlev (__mo_velocity_advection_MOD_velocity_tendencies, 151)
nproma (__mo_loopindices_MOD_get_indices_e, 135)
nrdmax (__mo_velocity_advection_MOD_velocity_tendencies, 151)
timer_intp (__mo_icon_interpolation_scalar_MOD_cells2verts_scalar_ri, 1200)
timer_solve_nh_veltend (__mo_velocity_advection_MOD_velocity_tendencies, 163)
timer_top (__mo_real_timer_MOD_timer_stop, 510)
timers_level (__mo_velocity_advection_MOD_velocity_tendencies, 163)
rt%active_under (__mo_real_timer_MOD_timer_start, 382)
rt%call_n (__mo_real_timer_MOD_timer_stop, 525)
rt%last (__mo_real_timer_MOD_timer_stop, 523)
rt%mark1 (__mo_real_timer_MOD_timer_stop, 508)
rt%max (__mo_real_timer_MOD_timer_stop, 527)
rt%min (__mo_real_timer_MOD_timer_stop, 526)
rt%stat (__mo_real_timer_MOD_timer_stop, 513)
rt%tot (__mo_real_timer_MOD_timer_stop, 524)
srt%text (__mo_real_timer_MOD_real_timer_abort, 1268)
```

As you can see, it contains all the stuff from `p_patch%verts`.

**Comment by chovyy** [comment]
> Could you make a release of your newest version?

There is already a release: [v1.2.3](https://github.com/fortesg/fortrancallgraph/releases/tag/v1.2.3).

> Is it safe for eniac-scripts to use the master?

I would say yes.
