### ISSUE TITLE
FTG failes with abstract types in ICON

### ISSUE THREAD

**Issue by phmarti** [fortesg/fortrantestgenerator#17]
With recent changes in ICON 2.4.00 release candidate FTG stopped working for some of our standalones. IT fails on the abstract type `t_comm_pattern` in `parallel_infrastructure/mo_communication_types.f90`. 

The procedures defined in the type used to be simple arrays and everything worked fine.

Is FTG able to deal with abstract types and we simply hit a bug? Or is this a more fundamental problem?

We had standalones for the `solve_nh` and `update_surface` routines, but we cannot regenerate them in the latest version of ICON.

**Comment by chovyy** [comment]
Polymorphism is generally a problem, but in some cases it can work anyway. I'm currently on vacation and will try it myself in September. Thanks for reporting.

**Comment by chovyy** [comment]
> I guess, I will first fix 3 + 4 to see how far it takes us, I have created an FCG ticket therefore.

That was [quite easy](https://github.com/fortesg/fortrancallgraph/commit/8fb24189a16a1fb05c8d6019b3467906c56a2603). Please check out [v1.2.4 of FCG](https://github.com/fortesg/fortrancallgraph/releases/tag/v1.2.4).

**Comment by chovyy** [comment]
There are also some issues in the new templates of [FTG v1.6.0-beta](https://github.com/fortesg/fortrantestgenerator/releases/tag/v1.6.0-beta), but [v1.5.0](https://github.com/fortesg/fortrantestgenerator/releases/tag/v1.5.0) should work.

**Comment by chovyy** [comment]
> but v1.5.0 should work.

Unfortunately, not. I'm working on it.

**Comment by chovyy** [comment]
> Unfortunately, not. I'm working on it.

Yes, it does.

**Comment by chovyy** [comment]
Fixed in [v1.10.0](https://github.com/fortesg/fortrantestgenerator/releases/tag/v.1.10.0).
