### ISSUE TITLE
Migrate to Serialbox2

### ISSUE THREAD

**Issue by chovyy** [fortesg/fortrantestgenerator#9]
[I'm just working on it](https://github.com/fortesg/fortrantestgenerator/tree/serialbox2).

**Comment by clementval** [comment]
@chovyy Quick question to understand it well. Once you have generated the standalone test, do you still need to "special" serialbox2 version with FTG or a simple serialbox2 without FTG will suffice?

**Comment by chovyy** [comment]
It will need the [FTG frontend](https://github.com/eth-cscs/serialbox2/pull/134).

The code generated by FTG is based on templates. The standard templates included in this repository will all be based on serialbox2 and the FTG frontend (currently they are still based on [serialbox-ftg](https://github.com/fortesg/serialbox-ftg)) It might be possible to create templates that are based on vanilla serialbox2 or any other serialization framework, but without the FTG frontend the generated code will be more complicated and unreadable.

**Comment by clementval** [comment]
@chovyy Ok, thanks for the info

**Comment by chovyy** [comment]
See [release v1.3.0](https://github.com/fortesg/fortrantestgenerator/releases/tag/v1.3.0).
